CREATE TABLE `CANDIDATES`
(
	`ID`			INT(8) NOT NULL AUTO_INCREMENT,
	`NAME`			VARCHAR(255) NOT NULL,
	`AGE`			INT(8) NOT NULL,
	`REGION`		VARCHAR(255) NOT NULL,
	`SCHOOL`		VARCHAR(255) NOT NULL,
	`LEVEL`			VARCHAR(255) NOT NULL,
	`PHONE`			VARCHAR(255) NOT NULL,
	`REG_DATE`		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CHAT_ID`		INT(32) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `USERS`
(
	`CHAT_ID`		INT(32) NOT NULL,
	`FIRST_NAME`	VARCHAR(255) NOT NULL,
	`USERNAME`		VARCHAR(255) NOT NULL,
	`DATE`			TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`CHAT_ID`)
);

ALTER TABLE `CANDIDATES`
	ADD CONSTRAINT `CANDIDATES` FOREIGN KEY (`CHAT_ID`) REFERENCES `USERS`(`CHAT_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;